# Generated by Django 5.2.4 on 2025-09-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("title_word", models.TextField(db_index=True, max_length=100)),
                ("title_word_md5", models.TextField(db_index=True, max_length=32)),
                (
                    "title_word_normalized",
                    models.TextField(db_index=True, max_length=100),
                ),
                (
                    "title_word_normalized_md5",
                    models.TextField(db_index=True, max_length=32),
                ),
                ("text_html", models.TextField(max_length=250000)),
                ("text_md5", models.TextField(db_index=True, max_length=32)),
                (
                    "version",
                    models.PositiveSmallIntegerField(default=1, editable=False),
                ),
                ("row_creation_timestamp", models.DateTimeField(auto_now_add=True)),
                ("row_update_timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
