name: Deploy eDTLR Browser

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Setup ssh authorization
      env:
        SSH_PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
        SSH_PUBLIC_KEY: ${{secrets.PUBLIC_KEY}}
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$SSH_PUBLIC_KEY" | tr -d '\r' > ~/.ssh/id_rsa.pub
        chmod 644 ~/.ssh/id_rsa.pub
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        echo SSH agent started
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts
        ssh-keyscan ${{secrets.HOST}} >> ~/.ssh/known_hosts

    - name: Update
      run: ssh -p ${{secrets.SSH_PORT}} ${{secrets.USERNAME}}@${{secrets.HOST}} "cd browse && git pull && make update"

    - name: Cleanup
      run: rm -rf ~/.ssh
